# Default values for annotations-mapper.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
service:
  name: "" # The name of the service, should be defined in the specific app-configs folder.
  hasHealthcheck: "true"
replicaCount: 2
image:
  repository: coco/annotations-mapper
  pullPolicy: IfNotPresent
resources:
  requests:
    memory: 45Mi
  limits:
    memory: 256Mi
env:
  CONSUMER_GROUP: ""
  CONSUMER_TOPIC: ""
  PRODUCER_TOPIC: ""
